---
- name: "Check parameters"
  ansible.builtin.assert:
    that:
      - path_to_file is defined
      - upstream_namespace is defined
      - downstream_namespace is defined
    quiet: True
    fail_msg: "Missing required parameters."

- name: "Include rename vars in files with overrides"
  ansible.builtin.include_tasks: rename_vars_in_file_with_override.yml
  when: "'defaults/main.yml' in path_to_file"
  vars:
    upstream_value: "{{ upstream_name }}"
    downstream_value: "{{ downstream_name }}"

- name: "Include rename vars in files"
  ansible.builtin.include_tasks: rename_vars_in_file.yml
  when: "'defaults/main.yml' not in path_to_file"
  vars:
    upstream_value: "{{ upstream_name }}"
    downstream_value: "{{ downstream_name }}"

- name: "Include rename vars in files"
  ansible.builtin.include_tasks: rename_vars_in_file.yml
  vars:
    upstream_value: "{{ upstream_namespace }}"
    downstream_value: "{{ downstream_namespace }}"

- name: Revert false positive matches
  ansible.builtin.include_tasks: rename_vars_in_file.yml
  vars:
    upstream_value: "{{ string.match }}"
    downstream_value: "{{ string.replace }}"
  loop: "{{ post_processors_replacements | default([]) }}"
  loop_control:
    loop_var: string
  when: string.file is not defined or path_to_file is regex(string.file)
