---
- name: "Ensure required parameters are defined."
  ansible.builtin.assert:
    that:
      - tag is defined
    quiet: True

- name: "Define git command to execute."
  ansible.builtin.set_fact:
    git_command: "tag {{ tag }}"

- name: "Execute git command '{{ git_command }}'"
  ansible.builtin.include_tasks: run_git_command.yml
